-- Índices para las consultas más frecuentes: tenant_id (solo o con status o
-- la FK que se filtra) en tablas grandes y FKs de tablas de detalle.
-- Auditoría 13/09/2026: el stock se calculaba con groupBy sobre
-- stock_movements sin ningún índice.
CREATE INDEX IF NOT EXISTS "users_tenant_id_idx" ON "users"("tenant_id");
CREATE INDEX IF NOT EXISTS "user_permissions_permission_id_idx" ON "user_permissions"("permission_id");
CREATE INDEX IF NOT EXISTS "role_permissions_permission_id_idx" ON "role_permissions"("permission_id");
CREATE INDEX IF NOT EXISTS "user_roles_role_id_idx" ON "user_roles"("role_id");
CREATE INDEX IF NOT EXISTS "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");
CREATE INDEX IF NOT EXISTS "products_tenant_id_status_idx" ON "products"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "products_category_id_idx" ON "products"("category_id");
CREATE INDEX IF NOT EXISTS "products_brand_id_idx" ON "products"("brand_id");
CREATE INDEX IF NOT EXISTS "product_components_tenant_id_product_id_idx" ON "product_components"("tenant_id", "product_id");
CREATE INDEX IF NOT EXISTS "production_orders_tenant_id_status_idx" ON "production_orders"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "product_suppliers_tenant_id_idx" ON "product_suppliers"("tenant_id");
CREATE INDEX IF NOT EXISTS "product_suppliers_supplier_id_idx" ON "product_suppliers"("supplier_id");
CREATE INDEX IF NOT EXISTS "product_units_product_id_idx" ON "product_units"("product_id");
CREATE INDEX IF NOT EXISTS "product_units_sale_order_item_id_idx" ON "product_units"("sale_order_item_id");
CREATE INDEX IF NOT EXISTS "product_batches_product_id_idx" ON "product_batches"("product_id");
CREATE INDEX IF NOT EXISTS "stock_movements_tenant_id_product_id_idx" ON "stock_movements"("tenant_id", "product_id");
CREATE INDEX IF NOT EXISTS "stock_movements_reference_id_idx" ON "stock_movements"("reference_id");
CREATE INDEX IF NOT EXISTS "stock_movements_warehouse_id_idx" ON "stock_movements"("warehouse_id");
CREATE INDEX IF NOT EXISTS "suppliers_tenant_id_idx" ON "suppliers"("tenant_id");
CREATE INDEX IF NOT EXISTS "purchase_orders_tenant_id_status_idx" ON "purchase_orders"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "purchase_orders_supplier_id_idx" ON "purchase_orders"("supplier_id");
CREATE INDEX IF NOT EXISTS "purchase_order_items_purchase_order_id_idx" ON "purchase_order_items"("purchase_order_id");
CREATE INDEX IF NOT EXISTS "purchase_receipt_items_purchase_receipt_id_idx" ON "purchase_receipt_items"("purchase_receipt_id");
CREATE INDEX IF NOT EXISTS "sale_orders_customer_id_idx" ON "sale_orders"("customer_id");
CREATE INDEX IF NOT EXISTS "sale_orders_seller_id_idx" ON "sale_orders"("seller_id");
CREATE INDEX IF NOT EXISTS "guarantors_tenant_id_idx" ON "guarantors"("tenant_id");
CREATE INDEX IF NOT EXISTS "guarantors_sale_order_id_idx" ON "guarantors"("sale_order_id");
CREATE INDEX IF NOT EXISTS "sale_payments_sale_order_id_idx" ON "sale_payments"("sale_order_id");
CREATE INDEX IF NOT EXISTS "delivery_notes_tenant_id_status_idx" ON "delivery_notes"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "delivery_tracking_events_delivery_note_id_idx" ON "delivery_tracking_events"("delivery_note_id");
CREATE INDEX IF NOT EXISTS "down_payments_tenant_id_idx" ON "down_payments"("tenant_id");
CREATE INDEX IF NOT EXISTS "sale_order_items_sale_order_id_idx" ON "sale_order_items"("sale_order_id");
CREATE INDEX IF NOT EXISTS "sale_order_items_product_id_idx" ON "sale_order_items"("product_id");
CREATE INDEX IF NOT EXISTS "sale_combos_tenant_id_idx" ON "sale_combos"("tenant_id");
CREATE INDEX IF NOT EXISTS "invoice_items_invoice_id_idx" ON "invoice_items"("invoice_id");
CREATE INDEX IF NOT EXISTS "credit_notes_tenant_id_idx" ON "credit_notes"("tenant_id");
CREATE INDEX IF NOT EXISTS "credit_notes_invoice_id_idx" ON "credit_notes"("invoice_id");
CREATE INDEX IF NOT EXISTS "accounts_receivable_tenant_id_status_idx" ON "accounts_receivable"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "payment_records_tenant_id_idx" ON "payment_records"("tenant_id");
CREATE INDEX IF NOT EXISTS "payment_records_accounts_receivable_id_idx" ON "payment_records"("accounts_receivable_id");
CREATE INDEX IF NOT EXISTS "accounts_payable_tenant_id_status_idx" ON "accounts_payable"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "accounts_payable_supplier_id_idx" ON "accounts_payable"("supplier_id");
CREATE INDEX IF NOT EXISTS "supplier_payments_tenant_id_idx" ON "supplier_payments"("tenant_id");
CREATE INDEX IF NOT EXISTS "supplier_payments_accounts_payable_id_idx" ON "supplier_payments"("accounts_payable_id");
CREATE INDEX IF NOT EXISTS "leaves_tenant_id_idx" ON "leaves"("tenant_id");
CREATE INDEX IF NOT EXISTS "leaves_employee_id_idx" ON "leaves"("employee_id");
CREATE INDEX IF NOT EXISTS "leave_balances_tenant_id_idx" ON "leave_balances"("tenant_id");
CREATE INDEX IF NOT EXISTS "file_records_tenant_id_module_entity_type_entity_id_idx" ON "file_records"("tenant_id", "module", "entity_type", "entity_id");
CREATE INDEX IF NOT EXISTS "credit_bureau_checks_tenant_id_customer_id_idx" ON "credit_bureau_checks"("tenant_id", "customer_id");
CREATE INDEX IF NOT EXISTS "interest_components_tenant_id_idx" ON "interest_components"("tenant_id");
CREATE INDEX IF NOT EXISTS "interest_components_credit_config_id_idx" ON "interest_components"("credit_config_id");
CREATE INDEX IF NOT EXISTS "loans_tenant_id_status_idx" ON "loans"("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "loans_customer_id_idx" ON "loans"("customer_id");
CREATE INDEX IF NOT EXISTS "payment_receipts_loan_id_idx" ON "payment_receipts"("loan_id");
CREATE INDEX IF NOT EXISTS "payment_receipts_customer_id_idx" ON "payment_receipts"("customer_id");
CREATE INDEX IF NOT EXISTS "payment_receipt_items_receipt_id_idx" ON "payment_receipt_items"("receipt_id");
CREATE INDEX IF NOT EXISTS "sale_targets_tenant_id_idx" ON "sale_targets"("tenant_id");
CREATE INDEX IF NOT EXISTS "collection_visits_tenant_id_customer_id_idx" ON "collection_visits"("tenant_id", "customer_id");
CREATE INDEX IF NOT EXISTS "collection_visits_route_id_idx" ON "collection_visits"("route_id");
CREATE INDEX IF NOT EXISTS "payment_agreements_tenant_id_customer_id_idx" ON "payment_agreements"("tenant_id", "customer_id");
CREATE INDEX IF NOT EXISTS "collection_notes_tenant_id_customer_id_idx" ON "collection_notes"("tenant_id", "customer_id");
CREATE INDEX IF NOT EXISTS "pos_sessions_tenant_id_status_idx" ON "pos_sessions"("tenant_id", "status");
